### ISSUE TITLE
Cljs version

### ISSUE THREAD

**Issue by annapawlicka** [xsc/version-clj#1]
I was looking for a cljs version of this library and since I couldn't find it, I copied most of it into my project (added url to the original, https://github.com/annapawlicka/is-it-time/blob/master/src/is_it_time/compare.cljs) and changed whatever was needed to work with javascript. Have your thought about porting it to cljs and releasing? Not much would actually need to be changed.

**Comment by xsc** [comment]
@annapawlicka Hm, a lot of my projects should get some cljs support but I have put off really getting into cljx or lein-dalap so far... And I agree, not much would have to be changed (mainly the Java interop in `version-clj.split`).

I'm on (programming-free) vacation for the next two weeks so if you're getting impatient feel free to open a PR and I'll gladly merge it. Otherwise, I'll have a look at it afterwards.
